### ISSUE TITLE
Services don't seem to have ran since around 5pm yesterday

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_infrastructure#115]
**Describe the bug**
Looking at the logs in cloudwatch, satellite stopped running at 17:20 on June 22nd, NWPs at 14:34, PV at 16:48

**To Reproduce**
For satellite logs:
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fconsumer$252Fsat$252F

**Expected behavior**

**Additional context**
I reran terraform to see if that fixed it and it doesn't seem to have.

**Comment by jacobbieker** [comment]
NWP data was last update at 14:34 June 22nd too

**Comment by peterdudfield** [comment]
GSP last ran at 17.14 - https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fconsumer$252Fgsp$252F

**Comment by peterdudfield** [comment]
No issues on AWS - https://phd.aws.amazon.com/phd/home#/account/dashboard/open-issues

**Comment by peterdudfield** [comment]
There seem to be 50 tasks running on the ECS cluster - https://eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/clusters/Nowcasting-development/tasks

**Comment by jacobbieker** [comment]
A lot of those satellite ones in the 50 seem to have completed https://eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/clusters/Nowcasting-development/tasks/e61a847aef754d19aa5d9ceea351df37/details

**Comment by jacobbieker** [comment]
Maybe solution is to kill the satellite services if they are running for more than say, 30min? Can we do that in Fargate automatically?

Seems like they were just taking up all the resources with inactive ones.

**Comment by jacobbieker** [comment]
New satellite is running: https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fconsumer$252Fsat$252F/log-events/streaming$252Fsat-consumer$252F3a89b42188814b7e8a04e03c6d14a92b

**Comment by peterdudfield** [comment]
> Maybe solution is to kill the satellite services if they are running for more than say, 30min? Can we do that in Fargate automatically?
> 
> Seems like they were just taking up all the resources with inactive ones.

Yea, we could look into adding a maximum timeout, Its not something Ive done before though.

**Comment by jacobbieker** [comment]
This one might be having the same problem: https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fconsumer$252Fsat$252F/log-events/streaming$252Fsat-consumer$252F3a89b42188814b7e8a04e03c6d14a92b its not progressed past saving the HRV, even though its finished writing it. I'll open a bug here in Satip for it https://github.com/openclimatefix/Satip/issues/121

**Comment by jacobbieker** [comment]
Downgrading Satip to 2.9.15 which doesn't have the muiltiprocessing code, so should crash instead of hang at least.

**Comment by jacobbieker** [comment]
With the downgrade, satellite is now running properly

**Comment by jacobbieker** [comment]
For future, seems like the easiest option in Fargate could be to just wrap our commands in a timeout command: https://github.com/aws/containers-roadmap/issues/572

**Comment by peterdudfield** [comment]
NWP has run and satellite has run

**Comment by peterdudfield** [comment]
Forecast currently failing, but I think it just needs a bit longer, to get various GSP data

**Comment by peterdudfield** [comment]
Ill close this for now
