### ISSUE TITLE
Add route53 to eb application

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_infrastructure#26]
## Detailed Description
Add route53 i.e an internet address to elastic beanstalk application. 

## Context
Useful for people to access the api, and not give them a funny elastic beanstalk address. 
Might have to ask @flowirtz for help

**Comment by flowirtz** [comment]
ah yeah, I think rn we use Cloudflare for DNS, so might use that instead. But I'm sure it's possible in some way

**Comment by flowirtz** [comment]
I just added a DNS entry on Cloudflare to point to the Elastic Beanstalk load balancer.
You can now reach the dev stack via https://api-dev.nowcasting.io/.
