### ISSUE TITLE
Try kubernetes

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_infrastructure#29]
## Detailed Description
Try using kubernetic cluster

## Context
This make it easier to use airflow

## Possible Implementation
https://learn.hashicorp.com/tutorials/terraform/eks

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/nowcasting_infrastructure

**Comment by peterdudfield** [comment]
useful blog - https://blog.payara.fish/do-you-need-kubernetes#:~:text=Kubernetes%20is%20useful%20if%20you,should%20not%20invest%20in%20it.

**Comment by JackKelly** [comment]
Very interesting!  I've asked Twitter for their thoughts: https://twitter.com/jack_kelly/status/1486761283143749632

Feel free to add comments or questions to that twitter thread!

**Comment by JackKelly** [comment]
The Twitter thread I linked to above now has some really interesting replies :slightly_smiling_face:

**Comment by peterdudfield** [comment]
Ill close this for now. The general idea was to test dragster cant run kibentics tasks, but online it says it cant.
