### ISSUE TITLE
add vpn tunnel

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_infrastructure#41]
## Detailed Description
Add method that local user can logging to the VPC in the cloud.

## Context
This is useful for debugging

**Comment by peterdudfield** [comment]
notes:https://docs.google.com/document/d/1wbbbsxI5pkYqMgZJrndgzMqk3YpQtWNH1MZkQ93fV4U/edit#heading=h.b1g487idy5ii

A found a way to do it with a ssh tunnel through a bastion host. I think this is enough for the moment. 

```bash
ssh -i ~/.ssh/PD_2021_11_24.pem -N -L 5432:pv-development.ctdracdgtpk3.eu-west-1.rds.amazonaws.com:5432 ec2-user@ec2-54-74-1-239.eu-west-1.compute.amazonaws.com -v
```

```python
from nowcasting_datamodel.connection import Base_PV, DatabaseConnection
from nowcasting_datamodel.models.pv import PVSystemSQL, PVYield

db_url='postgresql://{username}:{password}@localhost:5432/pvdevelopment'

connection = DatabaseConnection(url=db_url, base=Base_PV, echo=True)

session = connection.get_session()
session.query(PVSystemSQL).first()
```

One future step could be an easy way to set up a ec2 machine (terraform) with everyones ssh keys on it

**Comment by JackKelly** [comment]
Great work!

This probably isn't relevant now but, just to connect the dots, [here are my notes](https://docs.google.com/document/d/1rzbLjTbAjbzBxqC-9VtVHgnPGYFN7zohFn2K2iL3CNs/edit#heading=h.shivkkunh08r) on doing something similar to connect to `donatello`'s server management web UI by SSH'ing into `leonardo`.

**Comment by peterdudfield** [comment]
Thanks, all useful stuff

I also put some notes [here](https://docs.google.com/document/d/1wbbbsxI5pkYqMgZJrndgzMqk3YpQtWNH1MZkQ93fV4U/edit#heading=h.b1g487idy5ii)
