### ISSUE TITLE
Upgrade to postgres 14.1

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_infrastructure#46]
## Detailed Description
Would be good to use latetst postgres version -> 14.1

![Screenshot 2022-02-18 at 15 38 23](https://user-images.githubusercontent.com/34686298/154713938-591d3be0-b8b4-498c-9270-477ab436cbd1.png)

## Possible Implementation
change code [here](https://github.com/openclimatefix/nowcasting_infrastructure/blob/main/terraform/modules/database/rds.tf#L7)

**Comment by lordsonfernando** [comment]
Hi i would like to contribute, i understand that engine version needs to be changed from 13.4 to 14.1 in the code.is that it?

**Comment by peterdudfield** [comment]
> Hi i would like to contribute, i understand that engine version needs to be changed from 13.4 to 14.1 in the code.is that it?

yes please. That would be great

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/nowcasting_infrastructure/pull/47

**Comment by peterdudfield** [comment]
@all-contributors please add @lordsonfernando for code
