### ISSUE TITLE
Research Dagster

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_infrastructure#9]
## Detailed Description
Run dagster locally and see what it can do. Would be interesting to see
- how it kicks off jobs - can it kick off AWS tasks on ECS?
- how to make jobs dependent on each other? 
- how it deals with error messages
- what informatino does the user get?
- how can this be deployed not locally

This will be useful for nowcasting project
<img width="651" alt="Screenshot 2022-01-11 at 11 05 48" src="https://user-images.githubusercontent.com/34686298/148942060-19b2d96e-ea52-4f10-b884-b97566951d0a.png">

**Comment by peterdudfield** [comment]
https://www.youtube.com/watch?v=dV1-j_laCq4

video on how to use run python functions. Uses `dagit` to visualise and run things

**Comment by peterdudfield** [comment]
Potential terraform setup for dagster/dagit service - https://github.com/datarootsio/terraform-aws-ecs-dagster

**Comment by peterdudfield** [comment]
Cant find anything about Dagster kicking on ECS tasks, but this could be done with python e.g.boto3

Airflow - has something called [ECSOperator](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/ecs.html) that does this

**Comment by peterdudfield** [comment]
The dagster task could be someting like this. Note this doesnt relaly show any logs, and say if its failed or not
```
import boto3
client = boto3.client('ecs')

# run task
response = client.run_task(
    taskDefinition='forecast',
    launchType='FARGATE',
    cluster='Nowcasting-development',
    platformVersion='LATEST',
    count=1,
    networkConfiguration={
        'awsvpcConfiguration': {
            'subnets': [
                'subnet-xyz',
            ],
            'assignPublicIp': 'ENABLED',
        }
    }
)

task_arn = [task['taskArn'] for task in response['tasks']][0]

# look if the task has ended
task_arns = []
import time
while task_arn not in task_arns:

    response = client.list_tasks(
        cluster='Nowcasting-development',
        family='forecast',
        desiredStatus='STOPPED',
    )

    task_arns = response['taskArns']
    time.sleep(1)
    print('Checking')

```

**Comment by peterdudfield** [comment]
Apache Airflow has a managed service - https://aws.amazon.com/managed-workflows-for-apache-airflow/

**Comment by peterdudfield** [comment]
Interesting cost analysis or running dagster as a service online

![Screenshot 2022-01-27 at 09 43 57](https://user-images.githubusercontent.com/34686298/151333593-37dcc936-1f98-49d3-9124-cb9d44816edf.png)

**Comment by peterdudfield** [comment]
A very AWS way to trigger something
s3 --> Lambda --> ECS task
https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html

**Comment by peterdudfield** [comment]
Dagster does have Kuberneter support, so one idea would be to move ECS to a kubenetics cluster

**Comment by JackKelly** [comment]
> one idea would be to move ECS to a kubenetics cluster

yeah, maybe we will need to bite the bullet and use k8s in order to get a really robust service running (with automatic failover etc.). But maybe we could dip our toes into k8s in the "least painful" way possible? :slightly_smiling_face:  (e.g. using as fully-managed k8s as possible!)

**Comment by peterdudfield** [comment]
Kubenetics was not that simple to set up

Ive asking online, kubenetrs will not solve the issue. 

Dagster is good for data pipeline all based in one docker image. Currently we don't have this set up.
